# Generated by Django 4.1.5 on 2023-02-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
