# Generated by Django 4.1.5 on 2023-02-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_alter_item_price'),
        ('customer_app', '0001_initial'),
        ('order_app', '0002_remove_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer_app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item_app.item'),
        ),
    ]
