# Generated by Django 4.1.5 on 2023-02-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_remove_order_time_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_period',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Morning', max_length=15),
        ),
    ]
